# Generated by Django 5.2.11 on 2026-02-24 18:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote_id', models.CharField(editable=False, max_length=15, unique=True, verbose_name='ID de Lote')),
                ('nombre', models.CharField(choices=[('Lechuga', 'Lechuga'), ('Albahaca', 'Albahaca'), ('Mostaza', 'Mostaza'), ('Menta', 'Menta'), ('Hierbabuena', 'Hierbabuena')], max_length=50)),
                ('variedad', models.CharField(blank=True, max_length=100)),
                ('fecha_siembra', models.DateField(default=django.utils.timezone.now)),
                ('sistema_produccion', models.CharField(choices=[('PLA', 'Plantinera'), ('MAD', 'Maduración'), ('VER', 'Vertical Wall')], default='PLA', max_length=3)),
                ('subsistema', models.CharField(choices=[('PLA-STD', 'Plantinera'), ('PLA-MICRO', 'Microgreens'), ('MAD-R1', 'Rack I'), ('MAD-R2', 'Rack II'), ('MAD-R3', 'Rack III'), ('MAD-R4', 'Rack IV'), ('VER-1', 'Vertical I'), ('VER-2', 'Vertical II')], default='PLA-STD', max_length=10, verbose_name='Ubicación')),
                ('cantidad_bandejas', models.PositiveIntegerField(default=1)),
                ('fecha_traspaso_real', models.DateField(blank=True, null=True, verbose_name='Fecha de traspaso')),
                ('estado', models.CharField(choices=[('GER', 'Germinacion'), ('VEG', 'Vegetativo'), ('FLO', 'Floracion'), ('COS', 'Cosecha'), ('FIN', 'Finalizado')], default='GER', max_length=3)),
                ('notas', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('stock_actual', models.FloatField(default=0)),
                ('unidad', models.CharField(choices=[('L', 'Litros'), ('ML', 'Mililitros'), ('KG', 'Kilogramos'), ('G', 'Gramos'), ('UN', 'Unidades')], max_length=2)),
                ('stock_minimo', models.FloatField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('firmado_por', models.CharField(max_length=100)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha_programada', models.DateTimeField()),
                ('prioridad', models.CharField(choices=[('A', 'Alta'), ('M', 'Media'), ('B', 'Baja')], default='M', max_length=1)),
                ('completada', models.BooleanField(default=False)),
                ('cultivo_asociado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operaciones.cultivo')),
            ],
        ),
    ]
