# Generated by Django 5.2.11 on 2026-02-24 21:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo_accion', models.CharField(choices=[('REGISTRO', 'Nuevo Registro'), ('TRASPASO', 'Traspaso de sistema'), ('EDICION', 'Edición de datos'), ('ELIMINACION', 'Eliminación'), ('COSECHA', 'Cosecha realizada')], max_length=20)),
                ('lote_id_afectado', models.CharField(max_length=20)),
                ('cultivo_nombre', models.CharField(max_length=50)),
                ('detalles', models.TextField()),
            ],
        ),
    ]
