# Generated by Django 5.2.11 on 2026-02-24 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0002_historialoperacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialoperacion',
            name='fecha_siembra_registrada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
