# Generated by Django 5.2.11 on 2026-02-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0003_historialoperacion_fecha_siembra_registrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialoperacion',
            name='subsistema_registrado',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
