# Generated by Django 5.2.11 on 2026-02-25 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0004_historialoperacion_subsistema_registrado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialoperacion',
            name='detalles',
        ),
        migrations.AddField(
            model_name='historialoperacion',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
