# Generated by Django 5.2.11 on 2026-02-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0005_remove_historialoperacion_detalles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialoperacion',
            name='detalles',
            field=models.TextField(default='Sin detalles'),
        ),
    ]
