# Generated by Django 5.2.11 on 2026-02-26 17:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0006_historialoperacion_detalles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='fecha_programada',
        ),
        migrations.AddField(
            model_name='tarea',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_completada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tarea',
            name='subsistema',
            field=models.CharField(choices=[('GENERAL', 'Sistema General'), ('PLA', 'Plantinera'), ('MAD', 'Maduración'), ('VER', 'Vertical Wall')], default='GENERAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='prioridad',
            field=models.CharField(choices=[('ALTA', '🔴 Crítica/Urgente'), ('MEDIA', '🟡 Rutina/Importante'), ('BAJA', '🔵 Mantenimiento/Baja')], default='MEDIA', max_length=10),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
