# Generated by Django 5.2.11 on 2026-02-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0007_remove_tarea_fecha_programada_tarea_descripcion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistroOperativo',
        ),
        migrations.AlterField(
            model_name='historialoperacion',
            name='detalles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='subsistema',
            field=models.CharField(choices=[('GENERAL', 'Sistema General'), ('PLA-STD', 'Plantinera'), ('PLA-MICRO', 'Microgreens'), ('MAD-R1', 'Rack I'), ('MAD-R2', 'Rack II'), ('MAD-R3', 'Rack III'), ('MAD-R4', 'Rack IV'), ('VER-1', 'Vertical I'), ('VER-2', 'Vertical II')], default='PLA-STD', max_length=20),
        ),
    ]
