# Generated by Django 5.2.11 on 2026-02-28 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0008_delete_registrooperativo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cultivo',
            old_name='notas',
            new_name='detalles',
        ),
    ]
