# Generated by Django 5.2.11 on 2026-03-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0009_rename_notas_cultivo_detalles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivo',
            name='detalles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
