# Generated by Django 5.2.11 on 2026-03-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0010_alter_cultivo_detalles_alter_tarea_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialoperacion',
            name='cantidad_anterior',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historialoperacion',
            name='cantidad_posterior',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historialoperacion',
            name='cultivo_nombre_anterior',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historialoperacion',
            name='cultivo_nombre_nuevo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historialoperacion',
            name='fecha_anterior',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historialoperacion',
            name='fecha_modificada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historialoperacion',
            name='fecha_siembra_traspaso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historialoperacion',
            name='subsistema_posterior',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historialoperacion',
            name='subsistema_previo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historialoperacion',
            name='cantidad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historialoperacion',
            name='cultivo_nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='subsistema',
            field=models.CharField(choices=[('GENERAL', 'Sistema General'), ('PLA-STD', 'Plantinera'), ('PLA-MICRO', 'Microgreens'), ('MAD-R1', 'Maduración Rack I'), ('MAD-R2', 'Maduración Rack II'), ('MAD-R3', 'Maduración Rack III'), ('MAD-R4', 'Maduración Rack IV'), ('VER-1', 'Vertical I'), ('VER-2', 'Vertical II')], default='PLA-STD', max_length=20),
        ),
    ]
