# Generated by Django 5.2.11 on 2026-04-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0011_historialoperacion_cantidad_anterior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialoperacion',
            name='rendimiento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
